<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pole_detector</name>
  <version>0.0.0</version>
  <description>点云找杆子(直径≈3cm)：3D包围盒裁剪 + XY平面圆拟合求杆水平位置(x,y)+半径，并给出飞机对准杆还需转的角(yaw_err)</description>
  <maintainer email="yk@todo.todo">yk</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>eigen</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
